linters <- lintr::linters_with_defaults(
  # Air formats R/ and tests are hand-aligned for parallel lines, so these only
  # fight Air or the alignment.
  commas_linter = NULL,
  indentation_linter = NULL,
  spaces_inside_linter = NULL,
  pipe_continuation_linter = NULL,
  brace_linter = NULL,
  line_length_linter = NULL,
  # Constants are SCREAMING_SNAKE_CASE.
  object_name_linter = lintr::object_name_linter(
    c("snake_case", "symbols", "SNAKE_CASE")
  ),
  # Readable names beat short ones.
  object_length_linter = NULL,
  # Can't see variables used in cli's {} interpolation, so nearly all hits are
  # false; R CMD check still catches undefined globals.
  object_usage_linter = NULL
)

exclusions <- list(
  # Generated by testthat, gitignored.
  "tests/testthat/_problems",
  # Third-party GRIMMER oracle code, kept verbatim on purpose.
  "tests/testthat/test-grimmer.R"
)

encoding <- "UTF-8"
