# Standalone file: do not edit by hand
# Source: https://github.com/lhdjung/unsum/blob/HEAD/R/standalone-last-export.R
# Generated by: usethis::use_standalone("lhdjung/unsum", "last-export")
# ----------------------------------------------------------------------
#
# ---
# repo: lhdjung/unsum
# file: standalone-last-export.R
# last-updated: 2026-10-03
# license: https://unlicense.org
# imports: [rlang (>= 1.1.0), cli (>= 3.0.0)]
# ---

# ## Changelog
# 2026-10-03:
# - Name the innermost export not called by package code, e.g., `inner()`
#   in `outer(inner())`
# - `name_last_export()` returns the export's own name, not, e.g., "FUN"
# - Match the user-called function by identity, not by name
# - Removed the `package_name` argument
# - Replaced `caller_env_last_export()` by `sys.frame(index_last_export())`
# - Sped up `arg_match_in_export()`, mostly for an unchanged default
# - Added version floors for rlang and cli
#
# 2026-04-18:
# - Added `name_last_export()`

# Throw an error that names the exported function the user called as the
# source; e.g., "Error in `exported_fn()`", not "Error in `internal_helper()`".
abort_in_export <- function(...) {
  cli::cli_abort(
    message = c(...),
    call = sys.frame(index_last_export()),
    .envir = parent.frame()
  )
}


# Similar to `abort_in_export()` but as an alternative to `match.arg()` /
# `rlang::arg_match()`. Advantage: If this function throws an error, it will
# name the exported function called by the user as the source of the problem.
# Arguments shared with `rlang::arg_match()` work as there.
arg_match_in_export <- function(arg, values = NULL, multiple = FALSE) {
  arg_name <- as.character(substitute(arg))

  # If values not provided, extract from the calling function's formals
  if (is.null(values)) {
    values <- formals(sys.function(sys.parent()))[[arg_name]]
    if (is.null(values)) {
      cli::cli_abort(
        "Internal error: {.arg {arg_name}} not found in calling function."
      )
    }
    values <- eval(values, envir = parent.frame())
  }

  # Early escape hatches for the typical cases: a single valid string, or the
  # default left unchanged, i.e., its first value
  if (!multiple) {
    if (is.character(arg) && length(arg) == 1L && arg %in% values) {
      return(arg)
    }
    if (identical(arg, values)) {
      return(values[[1L]])
    }
  }

  # This is retained for non-typical cases and for its characteristic error msg
  rlang::arg_match(
    arg = arg,
    values = values,
    multiple = multiple,
    error_arg = arg_name,
    error_call = sys.frame(index_last_export())
  )
}


# Frame number of the exported function the user called: the innermost export
# that wasn't called by package code. Matched by identity, so it's safe for
# `lapply()` and other functionals. This also finds `inner()` in
# `outer(inner())`, which R evaluates lazily within `outer()`. Without such an
# export on the stack, e.g., for an S3 method, this falls back to the outermost
# function from the package.
index_last_export <- function() {
  ns <- topenv(environment())
  exports <- mget(getNamespaceExports(ns), envir = ns, inherits = TRUE)
  parents <- sys.parents()
  frames <- seq_along(parents)
  is_export <- vapply(frames, function(i) {
    any(vapply(exports, identical, logical(1L), sys.function(i)))
  }, logical(1L))
  # An export may have another environment, e.g., if made by `Vectorize()`
  in_package <- is_export | vapply(frames, function(i) {
    identical(ns, topenv(environment(sys.function(i))))
  }, logical(1L))
  for (i in rev(which(is_export))) {
    # Follow the callers up, skipping functions from other packages
    parent <- parents[i]
    while (parent > 0L && !in_package[parent]) {
      parent <- parents[parent]
    }
    if (parent == 0L) {
      return(i)
    }
  }
  which(in_package)[1L]
}


# Name of the user-called function, even if it was called as, e.g., `FUN()`
name_last_export <- function() {
  index <- index_last_export()
  ns <- topenv(environment())
  exports <- mget(getNamespaceExports(ns), envir = ns, inherits = TRUE)
  is_match <- vapply(exports, identical, logical(1L), sys.function(index))
  if (any(is_match)) {
    return(names(exports)[is_match][1L])
  }
  # Fallback for a non-exported function: the name it was called by
  fn <- sys.call(index)[[1L]]
  if (is.name(fn)) {
    as.character(fn)
  } else if (is.call(fn)) {
    # Remove any package prefix (e.g., "pkg::fn" --> "fn")
    sub("^.*::", "", deparse(fn)[1L])
  }
}
